'use client';

import { useState, useMemo } from 'react';
import { agents } from '@/data/agents';

type Platform = 'vercel' | 'railway' | 'fly' | 'aws' | 'docker' | 'kubernetes' | 'local';
type OutputFormat = 'env' | 'docker' | 'compose' | 'github-actions' | 'vercel-json' | 'railway-toml' | 'fly-toml';

interface Config {
  platform: Platform;
  selectedAgents: string[];
  walletPrivateKey: boolean;
  sandboxMode: boolean;
  enableLogging: boolean;
  enableCaching: boolean;
  cacheTimeout: number;
  retryAttempts: number;
  customEndpoint: string;
}

const platforms: { id: Platform; name: string; icon: string; description: string }[] = [
  { id: 'vercel', name: 'Vercel', icon: '▲', description: 'Serverless deployment' },
  { id: 'railway', name: 'Railway', icon: '🚂', description: 'PaaS deployment' },
  { id: 'fly', name: 'Fly.io', icon: '🪰', description: 'Edge deployment' },
  { id: 'aws', name: 'AWS', icon: '☁️', description: 'Lambda / ECS' },
  { id: 'docker', name: 'Docker', icon: '🐳', description: 'Container' },
  { id: 'kubernetes', name: 'Kubernetes', icon: '☸️', description: 'K8s manifests' },
  { id: 'local', name: 'Local Dev', icon: '💻', description: '.env file' },
];

const outputFormats: { id: OutputFormat; name: string; platforms: Platform[] }[] = [
  { id: 'env', name: '.env File', platforms: ['vercel', 'railway', 'fly', 'aws', 'docker', 'kubernetes', 'local'] },
  { id: 'docker', name: 'Dockerfile', platforms: ['docker', 'railway', 'fly', 'aws'] },
  { id: 'compose', name: 'docker-compose.yml', platforms: ['docker', 'local'] },
  { id: 'github-actions', name: 'GitHub Actions', platforms: ['vercel', 'railway', 'fly', 'aws', 'docker'] },
  { id: 'vercel-json', name: 'vercel.json', platforms: ['vercel'] },
  { id: 'railway-toml', name: 'railway.toml', platforms: ['railway'] },
  { id: 'fly-toml', name: 'fly.toml', platforms: ['fly'] },
];

export default function EnvGenerator() {
  const [config, setConfig] = useState<Config>({
    platform: 'local',
    selectedAgents: [],
    walletPrivateKey: true,
    sandboxMode: true,
    enableLogging: true,
    enableCaching: false,
    cacheTimeout: 300,
    retryAttempts: 3,
    customEndpoint: '',
  });
  const [activeFormat, setActiveFormat] = useState<OutputFormat>('env');
  const [copied, setCopied] = useState<string | null>(null);

  const availableFormats = outputFormats.filter(f => f.platforms.includes(config.platform));

  const generateEnvContent = useMemo(() => {
    const lines: string[] = [
      '# x402 Agent Configuration',
      '# Generated by langoustine69.dev',
      '',
      '# ===================',
      '# Core Settings',
      '# ===================',
      '',
      `# Mode: ${config.sandboxMode ? 'Sandbox (free tier)' : 'Production'}`,
      `X402_SANDBOX_MODE=${config.sandboxMode}`,
      '',
    ];

    if (config.walletPrivateKey) {
      lines.push('# Wallet Configuration (NEVER commit this!)');
      lines.push('X402_WALLET_PRIVATE_KEY=your_private_key_here');
      lines.push('');
    }

    if (config.selectedAgents.length > 0) {
      lines.push('# ===================');
      lines.push('# Agent Endpoints');
      lines.push('# ===================');
      lines.push('');
      config.selectedAgents.forEach(id => {
        const agent = agents.find(a => a.id === id);
        if (agent) {
          const envName = agent.id.toUpperCase().replace(/-/g, '_');
          lines.push(`# ${agent.name}`);
          lines.push(`${envName}_ENDPOINT=${agent.railwayUrl || `https://api.langoustine69.dev/${agent.id}`}`);
          lines.push('');
        }
      });
    }

    if (config.enableLogging || config.enableCaching) {
      lines.push('# ===================');
      lines.push('# Optional Settings');
      lines.push('# ===================');
      lines.push('');
    }

    if (config.enableLogging) {
      lines.push('# Logging');
      lines.push('X402_LOG_LEVEL=info');
      lines.push('X402_LOG_REQUESTS=true');
      lines.push('');
    }

    if (config.enableCaching) {
      lines.push('# Caching');
      lines.push('X402_CACHE_ENABLED=true');
      lines.push(`X402_CACHE_TTL_SECONDS=${config.cacheTimeout}`);
      lines.push('');
    }

    lines.push('# Retry Configuration');
    lines.push(`X402_MAX_RETRIES=${config.retryAttempts}`);
    lines.push('X402_RETRY_DELAY_MS=1000');
    lines.push('');

    if (config.customEndpoint) {
      lines.push('# Custom Base URL (for testing)');
      lines.push(`X402_BASE_URL=${config.customEndpoint}`);
      lines.push('');
    }

    return lines.join('\n');
  }, [config]);

  const generateDockerfile = useMemo(() => {
    return `# x402 Agent Application
# Generated by langoustine69.dev

FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy application code
COPY . .

# Build (if TypeScript)
RUN npm run build 2>/dev/null || true

# Environment variables (set at runtime)
ENV NODE_ENV=production
ENV X402_SANDBOX_MODE=${config.sandboxMode}
${config.enableLogging ? 'ENV X402_LOG_LEVEL=info' : ''}
${config.enableCaching ? `ENV X402_CACHE_ENABLED=true\nENV X402_CACHE_TTL_SECONDS=${config.cacheTimeout}` : ''}

# Expose port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s \\
  CMD wget --quiet --tries=1 --spider http://localhost:3000/health || exit 1

# Start application
CMD ["npm", "start"]
`;
  }, [config]);

  const generateDockerCompose = useMemo(() => {
    return `# x402 Agent Stack
# Generated by langoustine69.dev

version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - X402_SANDBOX_MODE=${config.sandboxMode}
      - X402_WALLET_PRIVATE_KEY=\${X402_WALLET_PRIVATE_KEY}
${config.enableLogging ? '      - X402_LOG_LEVEL=info\n      - X402_LOG_REQUESTS=true' : ''}
${config.enableCaching ? `      - X402_CACHE_ENABLED=true\n      - X402_CACHE_TTL_SECONDS=${config.cacheTimeout}` : ''}
      - X402_MAX_RETRIES=${config.retryAttempts}
${config.selectedAgents.length > 0 ? config.selectedAgents.map(id => {
  const agent = agents.find(a => a.id === id);
  if (agent) {
    const envName = agent.id.toUpperCase().replace(/-/g, '_');
    return `      - ${envName}_ENDPOINT=${agent.railwayUrl || `https://api.langoustine69.dev/${agent.id}`}`;
  }
  return '';
}).join('\n') : ''}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

${config.enableCaching ? `  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped` : ''}
`;
  }, [config]);

  const generateGitHubActions = useMemo(() => {
    const deployStep = config.platform === 'vercel'
      ? `      - name: Deploy to Vercel
        uses: vercel/action@v1
        with:
          vercel-token: \${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: \${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: \${{ secrets.VERCEL_PROJECT_ID }}`
      : config.platform === 'railway'
      ? `      - name: Deploy to Railway
        uses: bervProject/railway-deploy@v1
        with:
          railway_token: \${{ secrets.RAILWAY_TOKEN }}`
      : config.platform === 'fly'
      ? `      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: \${{ secrets.FLY_API_TOKEN }}`
      : `      - name: Deploy
        run: echo "Add your deployment step here"`;

    return `# x402 Agent Deployment
# Generated by langoustine69.dev

name: Deploy x402 Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  X402_SANDBOX_MODE: ${config.sandboxMode}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          X402_SANDBOX_MODE: true

      - name: Build
        run: npm run build

${deployStep}

    environment:
      name: \${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
`;
  }, [config]);

  const generateVercelJson = useMemo(() => {
    return JSON.stringify({
      "$schema": "https://openapi.vercel.sh/vercel.json",
      "framework": "nextjs",
      "buildCommand": "npm run build",
      "env": {
        "X402_SANDBOX_MODE": config.sandboxMode.toString(),
        "X402_LOG_LEVEL": config.enableLogging ? "info" : "error",
        ...(config.enableCaching && { "X402_CACHE_ENABLED": "true" }),
      },
      "headers": [
        {
          "source": "/api/(.*)",
          "headers": [
            { "key": "Cache-Control", "value": config.enableCaching ? `s-maxage=${config.cacheTimeout}, stale-while-revalidate` : "no-store" }
          ]
        }
      ]
    }, null, 2);
  }, [config]);

  const generateRailwayToml = useMemo(() => {
    return `# x402 Agent on Railway
# Generated by langoustine69.dev

[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 3

[env]
NODE_ENV = "production"
X402_SANDBOX_MODE = "${config.sandboxMode}"
${config.enableLogging ? 'X402_LOG_LEVEL = "info"' : ''}
${config.enableCaching ? `X402_CACHE_ENABLED = "true"\nX402_CACHE_TTL_SECONDS = "${config.cacheTimeout}"` : ''}
X402_MAX_RETRIES = "${config.retryAttempts}"
`;
  }, [config]);

  const generateFlyToml = useMemo(() => {
    return `# x402 Agent on Fly.io
# Generated by langoustine69.dev

app = "x402-agent-app"
primary_region = "iad"

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"
  X402_SANDBOX_MODE = "${config.sandboxMode}"
${config.enableLogging ? '  X402_LOG_LEVEL = "info"' : ''}
${config.enableCaching ? `  X402_CACHE_ENABLED = "true"\n  X402_CACHE_TTL_SECONDS = "${config.cacheTimeout}"` : ''}
  X402_MAX_RETRIES = "${config.retryAttempts}"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "30s"
  timeout = "3s"
  path = "/health"
  method = "GET"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
`;
  }, [config]);

  const getContent = (format: OutputFormat): string => {
    switch (format) {
      case 'env': return generateEnvContent;
      case 'docker': return generateDockerfile;
      case 'compose': return generateDockerCompose;
      case 'github-actions': return generateGitHubActions;
      case 'vercel-json': return generateVercelJson;
      case 'railway-toml': return generateRailwayToml;
      case 'fly-toml': return generateFlyToml;
      default: return '';
    }
  };

  const copyToClipboard = async (format: OutputFormat) => {
    await navigator.clipboard.writeText(getContent(format));
    setCopied(format);
    setTimeout(() => setCopied(null), 2000);
  };

  const downloadFile = (format: OutputFormat) => {
    const content = getContent(format);
    const filename = format === 'env' ? '.env.example'
      : format === 'docker' ? 'Dockerfile'
      : format === 'compose' ? 'docker-compose.yml'
      : format === 'github-actions' ? 'deploy.yml'
      : format === 'vercel-json' ? 'vercel.json'
      : format === 'railway-toml' ? 'railway.toml'
      : 'fly.toml';
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const toggleAgent = (id: string) => {
    setConfig(prev => ({
      ...prev,
      selectedAgents: prev.selectedAgents.includes(id)
        ? prev.selectedAgents.filter(a => a !== id)
        : [...prev.selectedAgents, id]
    }));
  };

  return (
    <div className="space-y-8">
      {/* Platform Selection */}
      <div>
        <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
          1. Choose Your Platform
        </h2>
        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-3">
          {platforms.map(p => (
            <button
              key={p.id}
              onClick={() => {
                setConfig(prev => ({ ...prev, platform: p.id }));
                setActiveFormat('env');
              }}
              className={`p-4 rounded-xl border-2 transition-all text-center ${
                config.platform === p.id
                  ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/30'
                  : 'border-gray-200 dark:border-gray-700 hover:border-blue-300'
              }`}
            >
              <span className="text-2xl block mb-1">{p.icon}</span>
              <span className="font-medium text-sm block">{p.name}</span>
              <span className="text-xs text-gray-500 dark:text-gray-400">{p.description}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Configuration Options */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="p-6 bg-gray-50 dark:bg-gray-800 rounded-xl">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
            2. Configure Options
          </h2>
          <div className="space-y-4">
            <label className="flex items-center gap-3">
              <input
                type="checkbox"
                checked={config.sandboxMode}
                onChange={e => setConfig(prev => ({ ...prev, sandboxMode: e.target.checked }))}
                className="w-5 h-5 rounded border-gray-300"
              />
              <div>
                <span className="font-medium">Sandbox Mode</span>
                <span className="text-sm text-gray-500 dark:text-gray-400 block">
                  Use free tier for development
                </span>
              </div>
            </label>

            <label className="flex items-center gap-3">
              <input
                type="checkbox"
                checked={config.walletPrivateKey}
                onChange={e => setConfig(prev => ({ ...prev, walletPrivateKey: e.target.checked }))}
                className="w-5 h-5 rounded border-gray-300"
              />
              <div>
                <span className="font-medium">Include Wallet Key Placeholder</span>
                <span className="text-sm text-gray-500 dark:text-gray-400 block">
                  Add X402_WALLET_PRIVATE_KEY variable
                </span>
              </div>
            </label>

            <label className="flex items-center gap-3">
              <input
                type="checkbox"
                checked={config.enableLogging}
                onChange={e => setConfig(prev => ({ ...prev, enableLogging: e.target.checked }))}
                className="w-5 h-5 rounded border-gray-300"
              />
              <div>
                <span className="font-medium">Enable Logging</span>
                <span className="text-sm text-gray-500 dark:text-gray-400 block">
                  Log API requests for debugging
                </span>
              </div>
            </label>

            <label className="flex items-center gap-3">
              <input
                type="checkbox"
                checked={config.enableCaching}
                onChange={e => setConfig(prev => ({ ...prev, enableCaching: e.target.checked }))}
                className="w-5 h-5 rounded border-gray-300"
              />
              <div>
                <span className="font-medium">Enable Caching</span>
                <span className="text-sm text-gray-500 dark:text-gray-400 block">
                  Cache responses (reduces costs)
                </span>
              </div>
            </label>

            {config.enableCaching && (
              <div className="ml-8">
                <label className="text-sm font-medium block mb-1">Cache TTL (seconds)</label>
                <input
                  type="number"
                  value={config.cacheTimeout}
                  onChange={e => setConfig(prev => ({ ...prev, cacheTimeout: parseInt(e.target.value) || 300 }))}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700"
                />
              </div>
            )}

            <div>
              <label className="text-sm font-medium block mb-1">Retry Attempts</label>
              <select
                value={config.retryAttempts}
                onChange={e => setConfig(prev => ({ ...prev, retryAttempts: parseInt(e.target.value) }))}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700"
              >
                <option value={0}>No retries</option>
                <option value={1}>1 retry</option>
                <option value={3}>3 retries (recommended)</option>
                <option value={5}>5 retries</option>
              </select>
            </div>

            <div>
              <label className="text-sm font-medium block mb-1">Custom Base URL (optional)</label>
              <input
                type="text"
                value={config.customEndpoint}
                onChange={e => setConfig(prev => ({ ...prev, customEndpoint: e.target.value }))}
                placeholder="https://custom.endpoint.com"
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700"
              />
            </div>
          </div>
        </div>

        <div className="p-6 bg-gray-50 dark:bg-gray-800 rounded-xl">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
            3. Select Agents (optional)
          </h2>
          <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">
            Add agent endpoints to your config
          </p>
          <div className="max-h-80 overflow-y-auto space-y-2">
            {agents.filter(a => a.status === 'live').map(agent => (
              <label
                key={agent.id}
                className={`flex items-center gap-3 p-3 rounded-lg cursor-pointer transition-colors ${
                  config.selectedAgents.includes(agent.id)
                    ? 'bg-blue-100 dark:bg-blue-900/30'
                    : 'hover:bg-gray-100 dark:hover:bg-gray-700'
                }`}
              >
                <input
                  type="checkbox"
                  checked={config.selectedAgents.includes(agent.id)}
                  onChange={() => toggleAgent(agent.id)}
                  className="w-4 h-4 rounded border-gray-300"
                />
                <span className="text-xl">{agent.icon}</span>
                <div className="flex-1 min-w-0">
                  <span className="font-medium block truncate">{agent.name}</span>
                  <span className="text-xs text-gray-500 dark:text-gray-400">{agent.category}</span>
                </div>
              </label>
            ))}
          </div>
          {config.selectedAgents.length > 0 && (
            <button
              onClick={() => setConfig(prev => ({ ...prev, selectedAgents: [] }))}
              className="mt-3 text-sm text-red-600 hover:text-red-700"
            >
              Clear selection ({config.selectedAgents.length})
            </button>
          )}
        </div>
      </div>

      {/* Output */}
      <div>
        <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
          4. Your Configuration Files
        </h2>

        {/* Format tabs */}
        <div className="flex flex-wrap gap-2 mb-4">
          {availableFormats.map(f => (
            <button
              key={f.id}
              onClick={() => setActiveFormat(f.id)}
              className={`px-4 py-2 rounded-lg font-medium text-sm transition-colors ${
                activeFormat === f.id
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700'
              }`}
            >
              {f.name}
            </button>
          ))}
        </div>

        {/* Code output */}
        <div className="relative">
          <div className="absolute top-3 right-3 flex gap-2 z-10">
            <button
              onClick={() => copyToClipboard(activeFormat)}
              className={`px-4 py-2 rounded-lg font-medium text-sm transition-colors ${
                copied === activeFormat
                  ? 'bg-green-600 text-white'
                  : 'bg-gray-700 text-white hover:bg-gray-600'
              }`}
            >
              {copied === activeFormat ? '✓ Copied!' : 'Copy'}
            </button>
            <button
              onClick={() => downloadFile(activeFormat)}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg font-medium text-sm hover:bg-blue-700"
            >
              Download
            </button>
          </div>
          <pre className="p-4 bg-gray-900 text-gray-100 rounded-xl overflow-x-auto text-sm font-mono whitespace-pre max-h-96 overflow-y-auto">
            {getContent(activeFormat)}
          </pre>
        </div>
      </div>

      {/* Security Warning */}
      <div className="p-4 bg-amber-50 dark:bg-amber-900/30 border border-amber-200 dark:border-amber-800 rounded-xl">
        <div className="flex gap-3">
          <span className="text-2xl">⚠️</span>
          <div>
            <h3 className="font-semibold text-amber-800 dark:text-amber-200">Security Reminder</h3>
            <ul className="text-sm text-amber-700 dark:text-amber-300 mt-1 space-y-1">
              <li>• <strong>Never commit</strong> .env files with real keys to git</li>
              <li>• Add <code className="bg-amber-100 dark:bg-amber-800 px-1 rounded">.env</code> to your <code className="bg-amber-100 dark:bg-amber-800 px-1 rounded">.gitignore</code></li>
              <li>• Use platform secrets/environment variables for production</li>
              <li>• Rotate keys immediately if exposed</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
