'use client';

import { useState, useMemo } from 'react';
import { Agent } from '@/data/agents';

interface SdkGeneratorProps {
  agent: Agent;
}

type SdkLanguage = 'typescript' | 'python' | 'go' | 'rust';

interface SdkConfig {
  name: string;
  icon: string;
  ext: string;
  color: string;
}

const sdkLanguages: Record<SdkLanguage, SdkConfig> = {
  typescript: { name: 'TypeScript', icon: '📘', ext: 'ts', color: 'from-blue-500 to-blue-700' },
  python: { name: 'Python', icon: '🐍', ext: 'py', color: 'from-yellow-500 to-green-600' },
  go: { name: 'Go', icon: '🐹', ext: 'go', color: 'from-cyan-500 to-cyan-700' },
  rust: { name: 'Rust', icon: '🦀', ext: 'rs', color: 'from-orange-500 to-red-600' },
};

function toClassName(name: string): string {
  return name
    .split(/[\s-]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

function toSnakeCase(name: string): string {
  return name.toLowerCase().replace(/[\s-]+/g, '_');
}

function generateTypescriptSdk(agent: Agent): string {
  const className = toClassName(agent.name) + 'Client';
  const baseUrl = agent.railwayUrl || 'https://your-agent.railway.app';
  
  return `/**
 * ${agent.name} SDK - TypeScript Client
 * Generated by langoustine69.dev SDK Generator
 * 
 * Features:
 * - Full x402 micropayment flow
 * - Automatic retry with payment
 * - TypeScript types
 * - Error handling
 */

export interface ${className}Config {
  baseUrl?: string;
  /** Wallet address for x402 payments */
  walletAddress?: string;
  /** Payment handler for x402 - receives payment details, returns payment proof */
  paymentHandler?: (paymentDetails: X402PaymentDetails) => Promise<string>;
  /** Request timeout in ms (default: 30000) */
  timeout?: number;
  /** Max retries for transient failures (default: 3) */
  maxRetries?: number;
}

export interface X402PaymentDetails {
  accepts: Array<{
    scheme: string;
    network: string;
    maxAmountRequired: string;
    resource: string;
    description: string;
    mimeType: string;
    payTo: string;
    maxTimeoutSeconds: number;
    asset: string;
  }>;
  error: string;
}

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  paymentRequired?: boolean;
  paymentDetails?: X402PaymentDetails;
}

export class ${className} {
  private baseUrl: string;
  private walletAddress?: string;
  private paymentHandler?: (details: X402PaymentDetails) => Promise<string>;
  private timeout: number;
  private maxRetries: number;

  constructor(config: ${className}Config = {}) {
    this.baseUrl = config.baseUrl || '${baseUrl}';
    this.walletAddress = config.walletAddress;
    this.paymentHandler = config.paymentHandler;
    this.timeout = config.timeout || 30000;
    this.maxRetries = config.maxRetries || 3;
  }

  private async request<T>(
    endpoint: string,
    options: RequestInit = {},
    retryCount = 0
  ): Promise<ApiResponse<T>> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeout);

    try {
      const response = await fetch(\`\${this.baseUrl}\${endpoint}\`, {
        ...options,
        signal: controller.signal,
        headers: {
          'Content-Type': 'application/json',
          ...options.headers,
        },
      });

      clearTimeout(timeoutId);

      // Handle x402 Payment Required
      if (response.status === 402) {
        const paymentDetails: X402PaymentDetails = await response.json();
        
        if (this.paymentHandler) {
          // Attempt automatic payment
          try {
            const paymentProof = await this.paymentHandler(paymentDetails);
            
            // Retry with payment proof
            return this.request<T>(endpoint, {
              ...options,
              headers: {
                ...options.headers,
                'X-Payment-Proof': paymentProof,
              },
            }, retryCount);
          } catch (paymentError) {
            return {
              success: false,
              error: 'Payment failed',
              paymentRequired: true,
              paymentDetails,
            };
          }
        }

        return {
          success: false,
          error: 'Payment required - configure paymentHandler',
          paymentRequired: true,
          paymentDetails,
        };
      }

      if (!response.ok) {
        // Retry on transient errors
        if (retryCount < this.maxRetries && [502, 503, 504].includes(response.status)) {
          await this.delay(Math.pow(2, retryCount) * 1000);
          return this.request<T>(endpoint, options, retryCount + 1);
        }
        
        const errorText = await response.text();
        return { success: false, error: errorText || \`HTTP \${response.status}\` };
      }

      const data = await response.json();
      return { success: true, data };
    } catch (error) {
      clearTimeout(timeoutId);
      
      if (error instanceof Error && error.name === 'AbortError') {
        return { success: false, error: 'Request timeout' };
      }

      // Retry on network errors
      if (retryCount < this.maxRetries) {
        await this.delay(Math.pow(2, retryCount) * 1000);
        return this.request<T>(endpoint, options, retryCount + 1);
      }

      return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
    }
  }

  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  /** Health check - always free */
  async health(): Promise<ApiResponse<{ status: string; timestamp: string }>> {
    return this.request('/health');
  }

  /** Overview endpoint - typically free */
  async overview(params: Record<string, unknown> = {}): Promise<ApiResponse<unknown>> {
    return this.request('/entrypoints/overview/invoke', {
      method: 'POST',
      body: JSON.stringify(params),
    });
  }

  /** Detailed endpoint - may require x402 payment */
  async detailed(params: Record<string, unknown> = {}): Promise<ApiResponse<unknown>> {
    return this.request('/entrypoints/detailed/invoke', {
      method: 'POST',
      body: JSON.stringify(params),
    });
  }

  /** Full report endpoint - typically requires x402 payment */
  async fullReport(params: Record<string, unknown> = {}): Promise<ApiResponse<unknown>> {
    return this.request('/entrypoints/full-report/invoke', {
      method: 'POST',
      body: JSON.stringify(params),
    });
  }

  /** Generic entrypoint invocation */
  async invoke(entrypoint: string, params: Record<string, unknown> = {}): Promise<ApiResponse<unknown>> {
    return this.request(\`/entrypoints/\${entrypoint}/invoke\`, {
      method: 'POST',
      body: JSON.stringify(params),
    });
  }
}

// Usage example:
/*
import { ${className} } from './${toSnakeCase(agent.name)}_sdk';

const client = new ${className}({
  // Optional: configure automatic payments
  paymentHandler: async (details) => {
    // Implement your x402 payment logic here
    // Return the payment proof string
    return 'your-payment-proof';
  },
});

// Free endpoint
const health = await client.health();
console.log(health.data);

// Paid endpoint - will auto-pay if paymentHandler configured
const report = await client.fullReport({ query: 'example' });
if (report.paymentRequired) {
  console.log('Payment needed:', report.paymentDetails);
} else {
  console.log('Result:', report.data);
}
*/
`;
}

function generatePythonSdk(agent: Agent): string {
  const className = toClassName(agent.name) + 'Client';
  const baseUrl = agent.railwayUrl || 'https://your-agent.railway.app';
  
  return `"""
${agent.name} SDK - Python Client
Generated by langoustine69.dev SDK Generator

Features:
- Full x402 micropayment flow
- Automatic retry with payment
- Type hints
- Error handling
"""

import time
from typing import Any, Callable, Optional, TypedDict
from dataclasses import dataclass
import requests


class X402PaymentAccept(TypedDict):
    scheme: str
    network: str
    maxAmountRequired: str
    resource: str
    description: str
    mimeType: str
    payTo: str
    maxTimeoutSeconds: int
    asset: str


class X402PaymentDetails(TypedDict):
    accepts: list[X402PaymentAccept]
    error: str


@dataclass
class ApiResponse:
    success: bool
    data: Optional[Any] = None
    error: Optional[str] = None
    payment_required: bool = False
    payment_details: Optional[X402PaymentDetails] = None


class ${className}:
    """Client for ${agent.name} x402 agent."""
    
    def __init__(
        self,
        base_url: str = "${baseUrl}",
        wallet_address: Optional[str] = None,
        payment_handler: Optional[Callable[[X402PaymentDetails], str]] = None,
        timeout: int = 30,
        max_retries: int = 3,
    ):
        self.base_url = base_url.rstrip('/')
        self.wallet_address = wallet_address
        self.payment_handler = payment_handler
        self.timeout = timeout
        self.max_retries = max_retries
        self.session = requests.Session()
    
    def _request(
        self,
        endpoint: str,
        method: str = "GET",
        json_data: Optional[dict] = None,
        headers: Optional[dict] = None,
        retry_count: int = 0,
    ) -> ApiResponse:
        url = f"{self.base_url}{endpoint}"
        req_headers = {"Content-Type": "application/json"}
        if headers:
            req_headers.update(headers)
        
        try:
            response = self.session.request(
                method,
                url,
                json=json_data,
                headers=req_headers,
                timeout=self.timeout,
            )
            
            # Handle x402 Payment Required
            if response.status_code == 402:
                payment_details: X402PaymentDetails = response.json()
                
                if self.payment_handler:
                    try:
                        payment_proof = self.payment_handler(payment_details)
                        return self._request(
                            endpoint,
                            method,
                            json_data,
                            {**req_headers, "X-Payment-Proof": payment_proof},
                            retry_count,
                        )
                    except Exception:
                        return ApiResponse(
                            success=False,
                            error="Payment failed",
                            payment_required=True,
                            payment_details=payment_details,
                        )
                
                return ApiResponse(
                    success=False,
                    error="Payment required - configure payment_handler",
                    payment_required=True,
                    payment_details=payment_details,
                )
            
            if not response.ok:
                # Retry on transient errors
                if retry_count < self.max_retries and response.status_code in [502, 503, 504]:
                    time.sleep(2 ** retry_count)
                    return self._request(endpoint, method, json_data, headers, retry_count + 1)
                
                return ApiResponse(success=False, error=response.text or f"HTTP {response.status_code}")
            
            return ApiResponse(success=True, data=response.json())
            
        except requests.Timeout:
            return ApiResponse(success=False, error="Request timeout")
        except requests.RequestException as e:
            if retry_count < self.max_retries:
                time.sleep(2 ** retry_count)
                return self._request(endpoint, method, json_data, headers, retry_count + 1)
            return ApiResponse(success=False, error=str(e))
    
    def health(self) -> ApiResponse:
        """Health check - always free."""
        return self._request("/health")
    
    def overview(self, **params) -> ApiResponse:
        """Overview endpoint - typically free."""
        return self._request("/entrypoints/overview/invoke", "POST", params or {})
    
    def detailed(self, **params) -> ApiResponse:
        """Detailed endpoint - may require x402 payment."""
        return self._request("/entrypoints/detailed/invoke", "POST", params or {})
    
    def full_report(self, **params) -> ApiResponse:
        """Full report - typically requires x402 payment."""
        return self._request("/entrypoints/full-report/invoke", "POST", params or {})
    
    def invoke(self, entrypoint: str, **params) -> ApiResponse:
        """Generic entrypoint invocation."""
        return self._request(f"/entrypoints/{entrypoint}/invoke", "POST", params or {})


# Usage example:
"""
from ${toSnakeCase(agent.name)}_sdk import ${className}

def my_payment_handler(details: X402PaymentDetails) -> str:
    # Implement your x402 payment logic here
    return "your-payment-proof"

client = ${className}(
    payment_handler=my_payment_handler,  # Optional
)

# Free endpoint
health = client.health()
print(health.data)

# Paid endpoint
report = client.full_report(query="example")
if report.payment_required:
    print("Payment needed:", report.payment_details)
else:
    print("Result:", report.data)
"""
`;
}

function generateGoSdk(agent: Agent): string {
  const structName = toClassName(agent.name) + 'Client';
  const packageName = toSnakeCase(agent.name).replace(/_/g, '');
  const baseUrl = agent.railwayUrl || 'https://your-agent.railway.app';
  
  return `// Package ${packageName} provides a client for ${agent.name}
// Generated by langoustine69.dev SDK Generator
//
// Features:
// - Full x402 micropayment flow
// - Automatic retry with payment
// - Error handling
package ${packageName}

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

// X402PaymentAccept represents a payment option
type X402PaymentAccept struct {
	Scheme            string \`json:"scheme"\`
	Network           string \`json:"network"\`
	MaxAmountRequired string \`json:"maxAmountRequired"\`
	Resource          string \`json:"resource"\`
	Description       string \`json:"description"\`
	MimeType          string \`json:"mimeType"\`
	PayTo             string \`json:"payTo"\`
	MaxTimeoutSeconds int    \`json:"maxTimeoutSeconds"\`
	Asset             string \`json:"asset"\`
}

// X402PaymentDetails represents 402 payment requirements
type X402PaymentDetails struct {
	Accepts []X402PaymentAccept \`json:"accepts"\`
	Error   string              \`json:"error"\`
}

// PaymentHandler handles x402 payments and returns proof
type PaymentHandler func(details X402PaymentDetails) (string, error)

// ApiResponse wraps API responses
type ApiResponse struct {
	Success         bool
	Data            json.RawMessage
	Error           string
	PaymentRequired bool
	PaymentDetails  *X402PaymentDetails
}

// Config for ${structName}
type Config struct {
	BaseURL        string
	WalletAddress  string
	PaymentHandler PaymentHandler
	Timeout        time.Duration
	MaxRetries     int
}

// ${structName} is the API client
type ${structName} struct {
	baseURL        string
	walletAddress  string
	paymentHandler PaymentHandler
	timeout        time.Duration
	maxRetries     int
	httpClient     *http.Client
}

// New creates a new ${structName}
func New(cfg Config) *${structName} {
	if cfg.BaseURL == "" {
		cfg.BaseURL = "${baseUrl}"
	}
	if cfg.Timeout == 0 {
		cfg.Timeout = 30 * time.Second
	}
	if cfg.MaxRetries == 0 {
		cfg.MaxRetries = 3
	}

	return &${structName}{
		baseURL:        cfg.BaseURL,
		walletAddress:  cfg.WalletAddress,
		paymentHandler: cfg.PaymentHandler,
		timeout:        cfg.Timeout,
		maxRetries:     cfg.MaxRetries,
		httpClient:     &http.Client{Timeout: cfg.Timeout},
	}
}

func (c *${structName}) request(ctx context.Context, endpoint, method string, body interface{}, headers map[string]string, retryCount int) (*ApiResponse, error) {
	var bodyReader io.Reader
	if body != nil {
		jsonBody, err := json.Marshal(body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(jsonBody)
	}

	req, err := http.NewRequestWithContext(ctx, method, c.baseURL+endpoint, bodyReader)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", "application/json")
	for k, v := range headers {
		req.Header.Set(k, v)
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		if retryCount < c.maxRetries {
			time.Sleep(time.Duration(1<<retryCount) * time.Second)
			return c.request(ctx, endpoint, method, body, headers, retryCount+1)
		}
		return nil, err
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	// Handle x402 Payment Required
	if resp.StatusCode == 402 {
		var paymentDetails X402PaymentDetails
		if err := json.Unmarshal(respBody, &paymentDetails); err != nil {
			return nil, err
		}

		if c.paymentHandler != nil {
			proof, err := c.paymentHandler(paymentDetails)
			if err != nil {
				return &ApiResponse{
					Success:         false,
					Error:           "Payment failed",
					PaymentRequired: true,
					PaymentDetails:  &paymentDetails,
				}, nil
			}
			newHeaders := make(map[string]string)
			for k, v := range headers {
				newHeaders[k] = v
			}
			newHeaders["X-Payment-Proof"] = proof
			return c.request(ctx, endpoint, method, body, newHeaders, retryCount)
		}

		return &ApiResponse{
			Success:         false,
			Error:           "Payment required - configure PaymentHandler",
			PaymentRequired: true,
			PaymentDetails:  &paymentDetails,
		}, nil
	}

	if resp.StatusCode >= 400 {
		if retryCount < c.maxRetries && (resp.StatusCode == 502 || resp.StatusCode == 503 || resp.StatusCode == 504) {
			time.Sleep(time.Duration(1<<retryCount) * time.Second)
			return c.request(ctx, endpoint, method, body, headers, retryCount+1)
		}
		return &ApiResponse{Success: false, Error: fmt.Sprintf("HTTP %d: %s", resp.StatusCode, string(respBody))}, nil
	}

	return &ApiResponse{Success: true, Data: respBody}, nil
}

// Health checks the agent health - always free
func (c *${structName}) Health(ctx context.Context) (*ApiResponse, error) {
	return c.request(ctx, "/health", "GET", nil, nil, 0)
}

// Overview calls the overview endpoint - typically free
func (c *${structName}) Overview(ctx context.Context, params map[string]interface{}) (*ApiResponse, error) {
	return c.request(ctx, "/entrypoints/overview/invoke", "POST", params, nil, 0)
}

// Detailed calls the detailed endpoint - may require x402 payment
func (c *${structName}) Detailed(ctx context.Context, params map[string]interface{}) (*ApiResponse, error) {
	return c.request(ctx, "/entrypoints/detailed/invoke", "POST", params, nil, 0)
}

// FullReport calls the full report endpoint - typically requires x402 payment
func (c *${structName}) FullReport(ctx context.Context, params map[string]interface{}) (*ApiResponse, error) {
	return c.request(ctx, "/entrypoints/full-report/invoke", "POST", params, nil, 0)
}

// Invoke calls a generic entrypoint
func (c *${structName}) Invoke(ctx context.Context, entrypoint string, params map[string]interface{}) (*ApiResponse, error) {
	return c.request(ctx, "/entrypoints/"+entrypoint+"/invoke", "POST", params, nil, 0)
}
`;
}

function generateRustSdk(agent: Agent): string {
  const structName = toClassName(agent.name) + 'Client';
  const baseUrl = agent.railwayUrl || 'https://your-agent.railway.app';
  
  return `//! ${agent.name} SDK - Rust Client
//! Generated by langoustine69.dev SDK Generator
//!
//! Features:
//! - Full x402 micropayment flow
//! - Automatic retry with payment
//! - Error handling

use reqwest::{Client, Response, StatusCode};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::time::Duration;
use thiserror::Error;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct X402PaymentAccept {
    pub scheme: String,
    pub network: String,
    #[serde(rename = "maxAmountRequired")]
    pub max_amount_required: String,
    pub resource: String,
    pub description: String,
    #[serde(rename = "mimeType")]
    pub mime_type: String,
    #[serde(rename = "payTo")]
    pub pay_to: String,
    #[serde(rename = "maxTimeoutSeconds")]
    pub max_timeout_seconds: i32,
    pub asset: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct X402PaymentDetails {
    pub accepts: Vec<X402PaymentAccept>,
    pub error: String,
}

#[derive(Debug, Error)]
pub enum SdkError {
    #[error("HTTP error: {0}")]
    Http(#[from] reqwest::Error),
    #[error("Payment required")]
    PaymentRequired(X402PaymentDetails),
    #[error("Payment failed: {0}")]
    PaymentFailed(String),
    #[error("API error: {0}")]
    Api(String),
}

#[derive(Debug, Clone)]
pub struct ApiResponse<T> {
    pub success: bool,
    pub data: Option<T>,
    pub error: Option<String>,
    pub payment_required: bool,
    pub payment_details: Option<X402PaymentDetails>,
}

pub type PaymentHandler = Box<dyn Fn(&X402PaymentDetails) -> Result<String, String> + Send + Sync>;

pub struct ${structName} {
    base_url: String,
    client: Client,
    max_retries: u32,
    payment_handler: Option<PaymentHandler>,
}

impl ${structName} {
    pub fn new() -> Self {
        Self::with_config("${baseUrl}", None)
    }

    pub fn with_config(base_url: &str, payment_handler: Option<PaymentHandler>) -> Self {
        let client = Client::builder()
            .timeout(Duration::from_secs(30))
            .build()
            .expect("Failed to create HTTP client");

        Self {
            base_url: base_url.trim_end_matches('/').to_string(),
            client,
            max_retries: 3,
            payment_handler,
        }
    }

    async fn request<T: for<'de> Deserialize<'de>>(
        &self,
        endpoint: &str,
        method: &str,
        body: Option<&HashMap<String, serde_json::Value>>,
        headers: Option<HashMap<String, String>>,
        retry_count: u32,
    ) -> Result<ApiResponse<T>, SdkError> {
        let url = format!("{}{}", self.base_url, endpoint);
        
        let mut req = match method {
            "POST" => self.client.post(&url),
            _ => self.client.get(&url),
        };

        req = req.header("Content-Type", "application/json");
        
        if let Some(h) = &headers {
            for (k, v) in h {
                req = req.header(k.as_str(), v.as_str());
            }
        }

        if let Some(b) = body {
            req = req.json(b);
        }

        let response = req.send().await?;
        let status = response.status();

        // Handle x402 Payment Required
        if status == StatusCode::PAYMENT_REQUIRED {
            let payment_details: X402PaymentDetails = response.json().await?;
            
            if let Some(handler) = &self.payment_handler {
                match handler(&payment_details) {
                    Ok(proof) => {
                        let mut new_headers = headers.unwrap_or_default();
                        new_headers.insert("X-Payment-Proof".to_string(), proof);
                        return self.request(endpoint, method, body, Some(new_headers), retry_count).await;
                    }
                    Err(e) => {
                        return Ok(ApiResponse {
                            success: false,
                            data: None,
                            error: Some(format!("Payment failed: {}", e)),
                            payment_required: true,
                            payment_details: Some(payment_details),
                        });
                    }
                }
            }

            return Ok(ApiResponse {
                success: false,
                data: None,
                error: Some("Payment required - configure payment_handler".to_string()),
                payment_required: true,
                payment_details: Some(payment_details),
            });
        }

        if !status.is_success() {
            if retry_count < self.max_retries && matches!(status.as_u16(), 502 | 503 | 504) {
                tokio::time::sleep(Duration::from_secs(2u64.pow(retry_count))).await;
                return self.request(endpoint, method, body, headers, retry_count + 1).await;
            }
            
            let error_text = response.text().await.unwrap_or_default();
            return Ok(ApiResponse {
                success: false,
                data: None,
                error: Some(format!("HTTP {}: {}", status.as_u16(), error_text)),
                payment_required: false,
                payment_details: None,
            });
        }

        let data: T = response.json().await?;
        Ok(ApiResponse {
            success: true,
            data: Some(data),
            error: None,
            payment_required: false,
            payment_details: None,
        })
    }

    /// Health check - always free
    pub async fn health(&self) -> Result<ApiResponse<serde_json::Value>, SdkError> {
        self.request("/health", "GET", None, None, 0).await
    }

    /// Overview endpoint - typically free
    pub async fn overview(&self, params: HashMap<String, serde_json::Value>) -> Result<ApiResponse<serde_json::Value>, SdkError> {
        self.request("/entrypoints/overview/invoke", "POST", Some(&params), None, 0).await
    }

    /// Detailed endpoint - may require x402 payment
    pub async fn detailed(&self, params: HashMap<String, serde_json::Value>) -> Result<ApiResponse<serde_json::Value>, SdkError> {
        self.request("/entrypoints/detailed/invoke", "POST", Some(&params), None, 0).await
    }

    /// Full report - typically requires x402 payment
    pub async fn full_report(&self, params: HashMap<String, serde_json::Value>) -> Result<ApiResponse<serde_json::Value>, SdkError> {
        self.request("/entrypoints/full-report/invoke", "POST", Some(&params), None, 0).await
    }

    /// Generic entrypoint invocation
    pub async fn invoke(&self, entrypoint: &str, params: HashMap<String, serde_json::Value>) -> Result<ApiResponse<serde_json::Value>, SdkError> {
        self.request(&format!("/entrypoints/{}/invoke", entrypoint), "POST", Some(&params), None, 0).await
    }
}

impl Default for ${structName} {
    fn default() -> Self {
        Self::new()
    }
}
`;
}

export default function SdkGenerator({ agent }: SdkGeneratorProps) {
  const [language, setLanguage] = useState<SdkLanguage>('typescript');
  const [copied, setCopied] = useState(false);

  const generatedCode = useMemo(() => {
    switch (language) {
      case 'typescript':
        return generateTypescriptSdk(agent);
      case 'python':
        return generatePythonSdk(agent);
      case 'go':
        return generateGoSdk(agent);
      case 'rust':
        return generateRustSdk(agent);
      default:
        return '';
    }
  }, [agent, language]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const config = sdkLanguages[language];
    const filename = `${toSnakeCase(agent.name)}_sdk.${config.ext}`;
    const blob = new Blob([generatedCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-gray-800/50 rounded-xl border border-gray-700 overflow-hidden">
      <div className="p-4 border-b border-gray-700">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold text-white flex items-center gap-2">
            <span className="text-2xl">🔧</span>
            SDK Generator
          </h3>
          <div className="flex gap-2">
            <button
              onClick={handleCopy}
              className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 text-white text-sm rounded-lg transition-colors flex items-center gap-1.5"
            >
              {copied ? '✓ Copied!' : '📋 Copy'}
            </button>
            <button
              onClick={handleDownload}
              className="px-3 py-1.5 bg-[#ff6b9d] hover:bg-[#ff5588] text-white text-sm rounded-lg transition-colors flex items-center gap-1.5"
            >
              ⬇️ Download
            </button>
          </div>
        </div>

        {/* Language selector */}
        <div className="flex flex-wrap gap-2">
          {(Object.entries(sdkLanguages) as [SdkLanguage, SdkConfig][]).map(([key, config]) => (
            <button
              key={key}
              onClick={() => setLanguage(key)}
              className={`px-3 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-2 ${
                language === key
                  ? `bg-gradient-to-r ${config.color} text-white shadow-lg`
                  : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
              }`}
            >
              <span>{config.icon}</span>
              {config.name}
            </button>
          ))}
        </div>
      </div>

      {/* Code preview */}
      <div className="relative">
        <pre className="p-4 overflow-x-auto text-sm text-gray-300 max-h-[500px] overflow-y-auto">
          <code>{generatedCode}</code>
        </pre>
        
        {/* Gradient fade at bottom */}
        <div className="absolute bottom-0 left-0 right-0 h-12 bg-gradient-to-t from-gray-800/90 to-transparent pointer-events-none" />
      </div>

      {/* Features list */}
      <div className="p-4 border-t border-gray-700 bg-gray-800/30">
        <h4 className="text-sm font-semibold text-gray-400 mb-2">SDK Features:</h4>
        <div className="flex flex-wrap gap-2">
          {[
            '✨ Full x402 payment flow',
            '🔄 Auto-retry on failure',
            '⚡ Configurable timeout',
            '🔐 Payment handler hook',
            '📝 Type definitions',
          ].map((feature) => (
            <span
              key={feature}
              className="px-2 py-1 bg-gray-700/50 rounded text-xs text-gray-400"
            >
              {feature}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
